#!/bin/sh
# postinstall script for signature pdf

set -e

# Droits sur les fichiers
chgrp -R www-data /~#LIBPATH#~data
chgrp -R www-data /~#LIBPATH#~pdf

chmod -R g+rwx /~#LIBPATH#~data
chmod -R g+rwx /~#LIBPATH#~pdf

# Activation de la conf apache2
mkdir -p /etc/apache2/conf-available
ln -sf ../../~#PKGNAME#~/apache.conf /etc/apache2/conf-available/signaturepdf.conf

a2enconf signaturepdf
systemctl reload apache2
