name: Build debian package (.deb)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install git
      run: sudo apt install git

    - name: Copie des fichiers dans le dossier debian
      run: |
        mkdir -p .debian/usr/share/signaturepdf
        git clone . .debian/usr/share/signaturepdf
        rm -rf .debian/usr/share/signaturepdf/.git

    - name: Set date / time
      run: |
        echo "RELEASE_DATE=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

    - name: build-deb-action
      uses: jiro4989/build-deb-action@v3
      with:
        package: signaturepdf
        package_root: .debian
        maintainer: 24ème <equipe@24eme.fr>
        version: ${{ env.RELEASE_DATE }}
        depends: php, pdftk, librsvg2-bin, imagemagick, potrace, ghostscript, locales
        arch: any
        desc: Outils de signature PDF en ligne libre et open-source

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: signaturepdf-${{ env.RELEASE_DATE }}-${{ github.ref_name }}.deb
        path: ./*.deb

